### ISSUE TITLE
Please add your modified source code

### ISSUE THREAD

**Issue by yochananmarqos** [rizalmart/gtock#1]
I'm sure I'm not the only one who would like to see your work porting this to Python 3 & Gtk 3.

**Comment by rizalmart** [comment]
> I'm sure I'm not the only one who would like to see your work porting this to Python 3 & Gtk 3.

The initial release was the first  modified source code. However due to GNOME developer recommendation to rename the project. I will republish the source code with complete modifications and overhaul

UPDATE: The source code has been republished

**Comment by yochananmarqos** [comment]
Where has the source been published? I see nothing that has changed in this repo except for the name change.
