### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by zypb3fx** [rizalmart/gtock#3]
For me it did not work, sometimes opens the program but does not save anything, nor as root, sometimes shows all the entries of the contrab and sometimes does not show anything, I use Mint Mate 21.1 and I would like to know with remove the gtock, I installed by the instructions of the link: https://askubuntu.com/questions/1459062/how-to-install-gnome-schedule-on-ubuntu-22-04

**Comment by rizalmart** [comment]
> For me it did not work, sometimes opens the program but does not save anything, nor as root, sometimes shows all the entries of the contrab and sometimes does not show anything, I use Mint Mate 21.1 and I would like to know with remove the gtock, I installed by the instructions of the link: https://askubuntu.com/questions/1459062/how-to-install-gnome-schedule-on-ubuntu-22-04

Did you install cronie?

**Comment by zypb3fx** [comment]
No, and does not appear in synaptic to install, but cron is installed

**Comment by rizalmart** [comment]
Fixed on commit c3c360f

**Comment by rizalmart** [comment]
> No, and does not appear in synaptic to install, but cron is installed

The bug has been fix. It turns out there is an error on reading dconf entry about cron
